<div id="storageAlert" class="alert-box">
	<a class="close">&times;</a>
	<h2>Storage Limits Reached</h2>
	<p>You have reached the Storage Limits you established for your site. You can change your Storage Limits by clicking the Settings tab.<span id="onSiteDisabled" class="hide"> Until you either change your settings to allow for more backups stored on your site or have removed some backups from your website, automatic backups will be not be uploaded to your site. They will still be available for pickup for up to 7 days after the backup is performed.</span></p>
</div>
<div id="storageWarning" class="alert-box warning">
	<a class="close">&times;</a>
	<h2>Storage Limits</h2>
	<p>You are approaching the Storage Limits you established for your site. You can change your Storage Limits by clicking the Settings tab.</p>
</div>
