<div id="siteNotAuthorized" class="alert-box">
	<a class="close">&times;</a>
	<h2>This site is not authorized to use the BackupBC app.</h2>
	<p>Please contact BackupBC to authorize use of this app on your site.</p>
</div>
<div id="authorizationNeeded" class="alert-box">
	<a class="close">&times;</a>
	<h2>Authorization Needed</h2>
	<p id="reauthNeeded">This app is not currently authorized to access your site. Please reauthorize the access by clicking below and following the instructions. Once complete, refresh this page to continue.</p>
	<p id="noToken" class="hide">This app has not yet been authorized to access your site's data. Please authorize access by clicking below and following the instructions. Once complete, refresh this page to continue.</p>
	<p><br><a id="reauthButton" href="https://ava-next.worldsecuresystems.com/api/oauth/authorize?client_id=backups-unlimited&version=2.0.0&state=0&response_type=code&redirect_uri=https://automatic.backupbc.com" target="reauthorize" class="button">Authorize Now</a></p>
</div>
