<div id="cloudStorageAlert" class="alert-box">
	<a class="close">&times;</a>
	<h2><span class="cloud-name"></span> Authorization Needed</h2>
	<p>BackupBC needs to authorize access to your <span class="cloud-name"></span> cloud storage account. Please click the button below to authorize access now. Until you've authorized access, backups cannot be uploaded to your cloud storage account and will only be available for download for 7 days after they've been performed.</p>
	<p><br><a href="#" id="cloudButton" class="button">Authorize Now</a></p>
</div>
