<h2 class="hybridFormHeader"><span class="hybridFormTitlewrap">Schedule Your Automatic Backups</span></h2>
<p>Your site will be backed up automatically based on your settings below.</p>
<span class="frequency"><input type="radio" name="frequency" value="daily" checked> Daily</span>
<span class="frequency"><input type="radio" name="frequency" value="weekly"> Weekly <span class="note">(Specify day below)</span></span>
<span class="frequency"><input type="radio" name="frequency" value="monthly"> Twice Monthly <span class="note">(1st and 15th each month)</span></span>
<br><br>
<select class="weeklyBackups hide" name="when">
	<option value="0">Sunday</option>
	<option value="1">Monday</option>
	<option value="2">Tuesday</option>
	<option value="3">Wednesday</option>
	<option value="4">Thursday</option>
	<option value="5">Friday</option>
	<option value="6">Saturday</option>
</select>
<p class="weeklyBackups hide"><strong>Tip:</strong> It's best to schedule your backups to run when your site is least likely to be updated with new files and data.</p>
