<h2 class="hybridFormHeader"><span class="hybridFormTitlewrap">Storage Limits</span></h2>
<p>When backups are saved on your website, the storage needs count toward the overall storage limitations for your account. For this reason, it's a good idea to set your desired Storage Limits below.</p>
<label>
	<span>
		Maximum number of backups to keep
		<i class="info-icon" data-target="max-num-popover" data-direction="right">Info</i>
		<div id="max-num-popover" class="popover">
			<div class="popover-box">
				<h1>Maximum number of backups</h1>
				<p>When you reach the maximum number of backups, you will receive an alert message.</p>
			</div>
			<div class="popover-arrow"></div>
		</div>
	</span>
	<input id="maxBackups" type="text"> backups
</label>
<label>
	<span>
		Maximum size of all backups combined
		<i class="info-icon" data-target="max-size-popover" data-direction="right">Info</i>
		<div id="max-size-popover" class="popover">
			<div class="popover-box">
				<h1>Maximum size of backups</h1>
				<p>When you reach the maximum size of all backups, you will receive an alert message.</p>
			</div>
			<div class="popover-arrow"></div>
		</div>
	</span>
	<input id="maxSize" type="text"> MB
</label>
