<h2 class="hybridFormHeader"><span class="hybridFormTitlewrap">Where do you want to store your backups?</span></h2>
<div id="uploadTo-site" class="backup-location" data-cloud="false">
	<label>
		<span class="cloud-option">
			<i class="cloud-check fa fa-check"><span> Ready</span></i><i class="info-icon pull-right" data-target="uploadto-site-popover" data-direction="right">Info</i><br/>
			<button id="websiteSetup" class="basic-button large-button"><i class="fa fa-cloud-upload"></i> Website</button>
		</span>
	</label>
	<div id="uploadto-site-popover" class="popover">
		<div class="popover-box">
			<h1>Website</h1>
			<p>Your backups will be stored on your website.</p>
		</div>
		<div class="popover-arrow"></div>
	</div>
</div>
